// ✅ DUMMY DATA - Using the exact JSON structure you provided
// This is your API response for UI flow testing
// API integration is COMMENTED OUT - using this for UI testing only

export const sampleCompletedResponse = {
  id: '80ddcee1-bc18-444a-96ca-a5c5e40bd984',
  product_url:
    'https://www.amazon.in/Nike-Court-Vision-Numeric_5-Black-White/dp/B098PC5X7X?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&smid=A2O5KR0Y95DC4B&th=1&psc=1',
  status: 'completed',
  current_stage: null,
  error_message: null,
  created_at: '2026-02-16T18:49:36.540787Z',
  updated_at: '2026-02-16T19:09:30.448104Z',
  completed_at: '2026-02-16T19:09:30.448002Z',
  metadata: {
    summary: {
      video_counts: {
        tiktok: 3,
        youtube: 10,
        instagram: 3,
        youtube_shorts: 10,
      },
      keywords_count: 12,
    },
    updated_at: '2026-02-16T19:09:30.447993+00:00',
    current_stage: null,
    completed_stages: [
      'fetch_product',
      'keywords',
      'video_scrape',
      'download',
      'analysis',
      'report',
      'scripts',
    ],
    stage_completed_at: {
      report: '2026-02-16T19:09:06.947769+00:00',
      scripts: '2026-02-16T19:09:30.447975+00:00',
      analysis: '2026-02-16T19:09:06.947769+00:00',
      download: '2026-02-16T19:09:06.947769+00:00',
      keywords: '2026-02-16T19:09:06.947769+00:00',
      video_scrape: '2026-02-16T19:09:06.947769+00:00',
      fetch_product: '2026-02-16T19:09:06.947769+00:00',
    },
  },
  report:
    '# Creative Agency Research Report\n\n**Generated:** 2026-02-16\n**Product link:** https://www.amazon.in/Nike-Court-Vision-Numeric_5-Black-White/dp/B098PC5X7X\n\n---\n\n## Report Summary\n\n- **Product Name**: Nike Mens Court Vision Low Next Nature Sneaker\n- **Category**: Men\'s Casual Shoes / Sneakers\n- **Report Date**: 2026-02-16\n\n### Key Metrics\n- Total Videos Found: 26\n- Engagement Rate: 8.5%\n- Average Views: 45,000\n- Keywords Generated: 12\n\n## Video Analysis Summary\n\n### Top Performing Videos\n1. Comparing Nike Air Force 1 and Nike Court Vision Low - 778,962 views\n2. Nike Sneakers Under ₹2000 - 1,636,443 views\n3. Nike Court Vision Low Review - 333,246 views\n\n### Video Distribution\n- YouTube: 10 videos\n- TikTok: 3 videos\n- Instagram: 3 videos\n- YouTube Shorts: 10 videos\n\n## Audience Insights\n\n### Target Demographics\n- Age: 18-35 years\n- Primary Interest: Fashion, Sneakers, Casual Wear\n- Platforms: Instagram, YouTube, TikTok\n\n### Key Themes from Comments\n- Affordability: Highly valued by audience\n- Comfort: Primary selling point\n- Sustainability: Growing interest in eco-friendly aspects\n- Comparison with Air Force 1: Most common discussion point\n\n## Marketing Recommendations\n\n1. **Focus on Affordability**: Emphasize the price advantage over competitors\n2. **Highlight Sustainability**: Showcase the 20% recycled materials\n3. **Create Comparison Content**: Leverage Air Force 1 comparisons\n4. **Influencer Partnerships**: Engage micro-influencers in sneaker space\n5. **User-Generated Content**: Encourage customers to share styling ideas\n\n## Competitive Analysis\n\n### Direct Competitors\n- Adidas Stan Smith\n- Puma Smash V2\n- New Balance 574\n- Converse Chuck Taylor All Star\n\n### Market Position\nNike Court Vision Low is positioned as an affordable alternative to Air Force 1 while offering better sustainability features.\n\n---\n\n*Report generated automatically by Product Intelligence Dashboard*',
  scripts:
    '# Video Scripts\n\n## TikTok Script 1: Unboxing\n\n[Visual: Unboxing the Nike Court Vision Low]\n**Hook**: "Ever wonder what makes these Nikes so special? Let\'s unbox and find out!"\n**Content**: Show the sneaker, highlight eco-friendly materials\n**CTA**: "Link in bio to grab your pair! 🌿👟"\n\n## Instagram Script 1: Styling Challenge\n\n[Visual: Different outfits with Nike Court Vision]\n**Hook**: "Can one sneaker fit every occasion? Let\'s style it!"\n**Content**: Gym look, office look, casual look\n**CTA**: "Hit the link in our bio to shop!"\n\n## YouTube Shorts Script 1: Comparison\n\n[Visual: Split screen comparison]\n**Hook**: "Nike Court Vision vs. Air Force 1: Which one\'s for you?"\n**Content**: Quick comparison of design, comfort, price\n**CTA**: "Comment below which one\'s your favorite!"',
  keywords: {
    subreddits: [
      'sneakers',
      'streetwear',
      'sneakerheads',
      'fashionreps',
      'malefashionadvice',
      'frugalmalefashion',
      'basketball',
      'Nike',
      'sneakercollecting',
      'buyitforlife',
    ],
    search_queries: [
      'Nike Court Vision Low Next Nature review',
      'Nike Court Vision Low unboxing',
      'Nike Court Vision Low Next Nature on feet',
      'Nike Court Vision Low vs Air Force 1',
      'Nike Court Vision Low basketball performance',
      'Nike Court Vision Low Next Nature style tips',
      'Nike Court Vision Low Next Nature durability test',
      'Nike Court Vision Low Next Nature comfort review',
      'Nike Court Vision Low Next Nature recycled materials',
      'Nike Court Vision Low Next Nature sneaker review',
      'Nike Court Vision Low Next Nature fit and sizing',
      'Nike Court Vision Low Next Nature casual wear',
    ],
  },
  stages: [
    {
      stage_name: 'fetch_product',
      stage_order: 0,
      status: 'completed',
      error_message: null,
      started_at: '2026-02-16T18:49:36.968176Z',
      completed_at: '2026-02-16T19:09:30.477096Z',
      metadata: {
        product_name: 'Nike Mens Court Vision Low Next Nature Sneaker',
        category: 'Casual Shoes',
        price_range: '$65-$75',
      },
    },
    {
      stage_name: 'keywords',
      stage_order: 1,
      status: 'completed',
      error_message: null,
      started_at: '2026-02-16T18:49:38.158566Z',
      completed_at: '2026-02-16T19:09:30.477096Z',
      metadata: {
        keywords_count: 12,
        subreddits_count: 10,
      },
    },
    {
      stage_name: 'video_scrape',
      stage_order: 2,
      status: 'completed',
      error_message: null,
      started_at: '2026-02-16T18:49:43.389300Z',
      completed_at: '2026-02-16T19:09:30.477096Z',
      metadata: {
        total_videos: 26,
        youtube: 10,
        tiktok: 3,
        instagram: 3,
        youtube_shorts: 10,
      },
    },
    {
      stage_name: 'download',
      stage_order: 3,
      status: 'completed',
      error_message: null,
      started_at: '2026-02-16T18:51:24.608947Z',
      completed_at: '2026-02-16T19:09:30.477096Z',
      metadata: {
        downloaded: 26,
        failed: 0,
      },
    },
    {
      stage_name: 'analysis',
      stage_order: 4,
      status: 'completed',
      error_message: null,
      started_at: '2026-02-16T18:52:06.290380Z',
      completed_at: '2026-02-16T19:09:30.477096Z',
      metadata: {
        analysis_type: 'sentiment_and_themes',
      },
    },
    {
      stage_name: 'report',
      stage_order: 5,
      status: 'completed',
      error_message: null,
      started_at: '2026-02-16T19:07:00.318863Z',
      completed_at: '2026-02-16T19:09:30.477096Z',
      metadata: {
        report_pages: 42,
        sections: 10,
      },
    },
    {
      stage_name: 'scripts',
      stage_order: 6,
      status: 'completed',
      error_message: null,
      started_at: '2026-02-16T19:09:06.947769Z',
      completed_at: '2026-02-16T19:09:30.477096Z',
      metadata: {
        scripts_generated: 3,
        platforms: ['tiktok', 'instagram', 'youtube'],
      },
    },
  ],
};

export const sampleRunningResponse = {
  id: '04b35603-d379-4d1f-a776-9425d82a0a45',
  product_url: 'https://www.myntra.com/casual-shoes/nike/nike-men-c1ty-shoes/31446158/buy',
  status: 'running',
  current_stage: 'video_scrape',
  error_message: null,
  created_at: '2026-02-17T04:39:41.684500Z',
  updated_at: '2026-02-17T04:39:45.456137Z',
  completed_at: null,
  metadata: {
    updated_at: '2026-02-17T04:39:45.453476+00:00',
    current_stage: 'video_scrape',
    completed_stages: ['fetch_product', 'keywords'],
    stage_completed_at: {
      keywords: '2026-02-17T04:39:45.453476+00:00',
      fetch_product: '2026-02-17T04:39:45.453476+00:00',
    },
  },
  stages: [
    {
      stage_name: 'fetch_product',
      stage_order: 0,
      status: 'completed',
      error_message: null,
      started_at: '2026-02-17T04:39:42.144616Z',
      completed_at: '2026-02-17T04:39:42.480682Z',
      metadata: {
        product_name: 'Nike Men C1ty Shoes',
      },
    },
    {
      stage_name: 'keywords',
      stage_order: 1,
      status: 'completed',
      error_message: null,
      started_at: '2026-02-17T04:39:42.480682Z',
      completed_at: '2026-02-17T04:39:45.453476Z',
      metadata: {
        keywords_count: 12,
      },
    },
    {
      stage_name: 'video_scrape',
      stage_order: 2,
      status: 'running',
      error_message: null,
      started_at: '2026-02-17T04:39:45.453476Z',
      completed_at: null,
      metadata: {
        progress: '45%',
      },
    },
    {
      stage_name: 'download',
      stage_order: 3,
      status: 'pending',
      error_message: null,
      started_at: null,
      completed_at: null,
      metadata: {},
    },
    {
      stage_name: 'analysis',
      stage_order: 4,
      status: 'pending',
      error_message: null,
      started_at: null,
      completed_at: null,
      metadata: {},
    },
    {
      stage_name: 'report',
      stage_order: 5,
      status: 'pending',
      error_message: null,
      started_at: null,
      completed_at: null,
      metadata: {},
    },
    {
      stage_name: 'scripts',
      stage_order: 6,
      status: 'pending',
      error_message: null,
      started_at: null,
      completed_at: null,
      metadata: {},
    },
  ],
};
